audit_header: false
title: Louisville Real Estate Video Blog with Rob St. John
description: Our mission at Omnipresent Property Group is to be your best resource for Louisville real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Omnipresent Property Group, your professional Louisville Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Rob St. John
  title:
  license_number:
  about_markdown: |
    Since 2012, Rob has dedicated his life to the real estate industry. His passion for client service is truly inspiring as Rob has made it his mission to provide such an amazing experience for his clients buying or selling their home that they have the confidence and comfort required to refer him to their friends and family members who are also looking to make a move.

    Rob's reputation with his clients has spread throughout the industry and he now helps other real estate agents, all over the country, by coaching and training them so that they too can provide their clients the same amazing experience.

    Rob continues to build his business as a Top Agent, and his team has been designed to help homeowners maximize their equity when selling their home. With his emphasis on marketing, leadership, and commitment to client service, Rob believes his team has only just begun. His goal is to provide the very best options to consumers who are thinking of selling their home by focusing on three things; selling the home for the highest price; ensuring clients walk away with the most money in their pocket; and providing an experience that is superior to anything else available in the market place.
  brand: Omnipresent Property Group
  brokerage: EXP Realty, LLC
  market: Louisville
  address: 5964 Timber Ridge Dr. Louisville, Ky 40059
  phone: 502-553-3277
  phone_type:
  phone2:
  phone2_type:
  email: rob@omnipresenthomes.com
  url: http://omnipresenthomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://myre.io/0nSfphNX8Huha
  second_CTA_text: Home Search
  second_CTA_URL: https://myre.io/0M9coepbc3Snd

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Louisville Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://myre.io/0nSfphNX8Huha

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Louisville Home?"
    CTA_text2: "Search the entire MLS for your Louisville home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://myre.io/0M9coepbc3Snd

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/realtor.robstjohn
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UCUgLzr_qM7IvwY1uYWhsjxQ
  twitter_url: https://www.twitter.com/luvilsrealtor
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Louisville Real Estate Podcast with Rob St. John'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Louisville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Omnipresent Property Group - your professional Louisville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Louisville, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Rob St. John'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Louisville Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#19469d'
  theme_color: '#00021a'
  accent_color: '#f5821f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
